import { useEffect, useState } from "react";
import { ArrowLeft, CheckCircle2, Code2, Download, FileCode2, RefreshCw, XCircle } from "lucide-react";
import { useNavigate } from "react-router-dom";
import { apiRequest } from "../../services/api";
import "./super-admin-developer-submissions.css";

type Submission={id:number;filename:string;language:string;description:string;content:string;status:string;remarks?:string|null;developer_name?:string;developer_email?:string;submitted_at:string};
export default function SuperAdminDeveloperSubmissions(){
 const navigate=useNavigate(); const [items,setItems]=useState<Submission[]>([]); const [selected,setSelected]=useState<Submission|null>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState(""); const [remarks,setRemarks]=useState("");
 const load=async()=>{setLoading(true);setError("");try{const r=await apiRequest<{submissions:Submission[]}>("/super-admin/developer-submissions");setItems(r.submissions??[]);if(selected){setSelected((r.submissions??[]).find(x=>x.id===selected.id)??null)}}catch(e){setError(e instanceof Error?e.message:"Unable to load submissions")}finally{setLoading(false)}};
 useEffect(()=>{void load()},[]);
 const review=async(status:string)=>{if(!selected)return;try{await apiRequest(`/super-admin/developer-submissions/${selected.id}`,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({status,remarks})});setRemarks("");await load()}catch(e){setError(e instanceof Error?e.message:"Unable to update submission")}};
 const download=()=>{if(!selected)return;const blob=new Blob([selected.content],{type:"text/plain;charset=utf-8"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=selected.filename;a.click();URL.revokeObjectURL(url)};
 return <div className="sds-page"><header><button onClick={()=>navigate("/app/super-admin")}><ArrowLeft size={16}/> Super Admin</button><div><Code2 size={19}/><strong>Developer Code Submissions</strong><span>Review normal project code before adding it to the platform structure.</span></div><button onClick={()=>void load()}><RefreshCw size={15}/> Refresh</button></header><main><section className="sds-list"><div className="sds-heading"><div><span>DEVELOPER WORKSPACE</span><h1>Submission Queue</h1></div><b>{items.filter(x=>x.status==="PENDING").length} pending</b></div>{loading?<p className="sds-muted">Loading submissions…</p>:items.length===0?<p className="sds-muted">No developer code has been submitted yet.</p>:items.map(item=><button key={item.id} className={`sds-item ${selected?.id===item.id?"active":""}`} onClick={()=>setSelected(item)}><FileCode2 size={18}/><div><strong>{item.filename}</strong><span>{item.developer_name||"Developer"} · {item.developer_email||""}</span></div><em className={item.status.toLowerCase()}>{item.status}</em></button>)}</section>{selected?<section className="sds-review"><div className="sds-review-head"><div><span>SUBMISSION #{selected.id}</span><h2>{selected.filename}</h2><p>{selected.description}</p></div><button onClick={download}><Download size={15}/> Download</button></div><div className="sds-meta"><span>Language <b>{selected.language}</b></span><span>Developer <b>{selected.developer_name||"—"}</b></span><span>Submitted <b>{new Date(selected.submitted_at).toLocaleString()}</b></span></div><pre>{selected.content}</pre><label>Super Admin remarks<textarea value={remarks} onChange={e=>setRemarks(e.target.value)} placeholder="Optional review note…" rows={3}/></label><div className="sds-actions"><button onClick={()=>void review("REJECTED")}><XCircle size={15}/> Reject</button><button onClick={()=>void review("REVIEWED")}><CheckCircle2 size={15}/> Mark Reviewed</button><button className="accept" onClick={()=>void review("ACCEPTED")}><CheckCircle2 size={15}/> Accept for Structure</button></div><p className="sds-safe">Acceptance records Super Admin approval. It does not execute the code or modify EduSphere system files automatically; the approved file can be downloaded and placed into the intended project structure manually.</p></section>:<section className="sds-review sds-empty"><Code2 size={35}/><h2>Select a submission</h2><p>Review the developer's code and description here.</p></section>}</main>{error&&<div className="sds-error">{error}</div>}</div>;
}
